version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: storage-mngmnt
      POSTGRES_USER: storage-mngmnt
      POSTGRES_DB: store-mngmnt
    volumes:
      - ./backend/pgdata:/var/lib/postgresql/data\
    ports:
      - "5432:5432"

  node:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
    ports:
      - "4000:4000"

  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - node
